// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/01-Vue3-SSR/06-vue3-ssr-pinia/src/views/about.vue
<template>
  <div class="app" style="border: 1px solid blue; margin: 10px">
    <h2>About</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>
  </div>
</template>

<script setup>
import { storeToRefs } from "pinia";
import { useHomeStore } from "../store/home";
let homeStore = useHomeStore();
let { count } = storeToRefs(homeStore);
function addCounter() {
  count.value++;
}
</script>

// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/03-React18-SSR/05-react18-ssr-redux/src/pages/about.jsx
import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { increment } from "../store/modules/home";

const About = function () {
  // const [counter, setCounter] = useState(300);
  // 1.从redux的store中读取数据
  const { counter } = useSelector((rootState) => {
    return {
      counter: rootState.home.counter,
    };
  });
  // 2.触发action
  const dispatch = useDispatch();
  function addCounter() {
    // setCounter(counter + 1);
    dispatch(increment(4));
  }
  return (
    <div className="About" style={{ border: "2px solid blue", margin: "20px" }}>
      <h3>About</h3>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
    </div>
  );
};

export default About;
