// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/01-Vue3-SSR/05-vue3-ssr-router/src/views/home.vue
<template>
  <div class="app" style="border: 1px solid green; margin: 10px">
    <h2>Home</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>
  </div>
</template>

<script setup>
import { ref } from "vue";
const count = ref(200);
function addCounter() {
  count.value++;
}
</script>

// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/03-React18-SSR/05-react18-ssr-redux/src/pages/home.jsx
import React, { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
// 导入了两个 action 函数
import { increment, fetchHomeData } from "../store/modules/home";

const Home = function () {
  // const [counter, setCounter] = useState(200);
  // 1.从redux的store中读取数据
  const { counter } = useSelector((rootState) => {
    return {
      counter: rootState.home.counter,
    };
  });

  // 2.触发action
  const dispatch = useDispatch();
  function addCounter() {
    // setCounter(counter + 1);
    dispatch(increment(2));
  }
  function getHomeData() {
    dispatch(fetchHomeData());
  }
  return (
    <div className="Home" style={{ border: "2px solid green", margin: "10px" }}>
      <h3>Home</h3>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
      <button onClick={getHomeData}>getHomeData</button>
    </div>
  );
};

export default Home;
