// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/02-Nuxt3/04-style-nuxt/pages/index.vue
<template>
  <hr />
  <div class="global-style">1.Home Page</div>
  <div class="global-style1">2.Home Page 全局样式</div>
  <div class="global-style2">3.Home Page 全局样式</div>
  <div class="local-style">4.Home Page 局部样式</div>

  <i class="iconfont icon-cart"></i>
  <i class="iconfont icon-edit"></i>
</template>
<style scoped lang="scss">
/* 1.手动导入全局样式 */
/* @import "~/assets/styles/variables.scss"; */

// as vb: 给这个模块起一个命名空间
// as * : 可以省略命名空间
// @use 和 @import
/* @use "~/assets/styles/variables.scss" as bv; */
/* @use "~/assets/styles/variables.scss" as *; */

.local-style {
  /* color: vb.$fsColor; */
  color: $fsColor;
  font-size: $fs20;
  @include border();
}
</style>

// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/04-Nextjs13/04-style-next/pages/index.tsx
import styles from "./index.module.scss";
import Image from "next/image";
import UserImg from "../assets/images/user.png";
export default function Home() {
  return (
    <>
      <h3>样式</h3>
      <div className="globel-style1">1.全局样式</div>
      <div className="global-style2">2.全局样式</div>
      <div className={styles["local-style1"]}>3.局部样式</div>
      <div className={styles.localStyle2}>4.局部样式</div>
      <div style={{ color: styles.primaryColor }}>5.使用scss导出的变量</div>
      <h3>public</h3>
      <Image src={"/feel.png"} alt="feel" width={140} height={140}></Image>
      <div className="box1-bg"></div>

      <h3>assets</h3>
      <Image src={UserImg} alt="feel"></Image>
      <div className="box2-bg"></div>

      <h3>字体图标</h3>
      <i className="iconfont icon-bianji icon"></i>
    </>
  );
}
