// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/01-Vue3-SSR/06-vue3-ssr-pinia/src/App.vue
<template>
  <div class="app" style="border: 1px solid red">
    <h2>Vue3 App</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>

    <div>
      <router-link to="/">
        <button>home</button>
      </router-link>
      <router-link to="/about">
        <button>about</button>
      </router-link>
    </div>
    <!-- 路由的占位 -->
    <router-view></router-view>
  </div>
</template>

<script setup>
import { ref } from "vue";
const count = ref(100);
function addCounter() {
  count.value++;
}
</script>

// coderwhyStudentCode/16、后端渲染SSR-Nuxt3和Nextjs/03-React18-SSR/02-react18-ssr-server-hydration/src/app.jsx
import React, { useState } from "react";
const App = function () {
  const [counter, setCounter] = useState(100);
  function addCounter() {
    setCounter(counter + 1);
  }
  return (
    <div className="app" style={{ border: "1px solid red;" }}>
      <h2>App</h2>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
    </div>
  );
};

export default App;
